[dependencies]
base = "0.11.3"
itertools = "0.2.1"

[package]
name = "hex-grid"
version = "0.1.0"
description = "A library for hex grid building"
repository = "https://github.com/edjcase/motoko_hex_grid"
keywords = [ "hex", "grid" ]
license = "MIT"

[dev-dependencies]
test = "1.0.1"